# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_update_email_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='line1',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='line2',
            field=models.CharField(choices=[('Moroni Ville', 'Moroni Ville'), ('Mitsamudu Anjouan', 'Mitsamudu Anjouan'), ('Fomboni Moheli', 'Fomboni Moheli'), ('Bambao Ngazidja', 'Bambao Ngazidja'), ('Hambou Ngazidja', 'Hambou Ngazidja'), ('Mbadjini Ouest', 'Mbadjini Ouest'), ('Mbadjini Est', 'Mbadjini Est'), ('Ouachili Ngazidja', 'Ouachili Ngazidja'), ('Hamahamet Ngazidja', 'Hamahamet Ngazidja'), ('Mitsamihuli Ngazidja', 'Mitsamihuli Ngazidja'), ('Itsandra Ngazidja', 'Itsandra Ngazidja'), ('Mremani Anjouan', 'Mremani Anjouan'), ('Domoni Anjouan', 'Domoni Anjouan'), ('Ouani Anjouan', 'Ouani Anjouan'), ('Sima Anjouan', 'Sima Anjouan'), ('Ngoumachoi Moheli', 'Ngoumachoi Moheli'), ('Djando Moheli', 'Djando Moheli')], default='', max_length=300, verbose_name='Region du bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='line3',
            field=models.CharField(choices=[('Ngazidja', 'Ngazidja'), ('Anjouan', 'Anjouan'), ('Moheli', 'Moheli'), ('Mayotte', 'Mayotte')], default='Ngazidja', max_length=250, verbose_name='Ile du bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='notes',
            field=models.TextField(blank=True, help_text="Dites nous tout ce qu'il savoir sur votre commande s'il vous plait", verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text="S'il s'agit de transfert de crédit, mettez le numéro du bénéficiaire", max_length=128, verbose_name='Numéro Téléphone'),
        ),
    ]
